---
title: "Untitled"
output: html_document
date: "2025-10-06"
---
```{r}
setwd("/Users/ezranwobodo/Downloads")
data = read.csv("housing.csv")

library(mgcv)
library(mgcViz)

summary(data)
```

```{r}
# Average out missing data
data = data %>% mutate_all(~ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x))

# Create new potentially useful features
data = transform(data, avg_rooms = total_rooms/households)
data = transform(data, avg_bedrooms = total_bedrooms/households)
data = transform(data, pop_per_house = population/households)
data = transform(data, is_max = median_house_value>500000)
```

```{r}
# Plots to show some data quirks
plot(data$pop_per_house,data$median_house_value)
plot(data$avg_rooms,data$median_house_value)
hist(data$housing_median_age,breaks=seq(0,52,l=53))
plot(data$median_income,data$median_house_value)
```

```{r}
# Some code to filter outliers. Commented out for now

# data = filter(data, pop_per_house < 30)
# data = filter(data, avg_rooms <30)
# data = filter(data, housing_median_age<52)
# data = filter(data, median_house_value != 500001)
```


```{r}
# Train-test split
n=nrow(data)
sample <- sample.int(n = n, size = floor(.75*n), replace = F)
train = data[sample,]
test = data[-sample,]
```

```{r}
# Step-wise algorithm to choose model based on AIC. Results in a model including every predictor but it's also useful to show which predictors are most relevant

library(MASS)
null = lm(median_house_value ~ 1,data=train)
full = lm(median_house_value ~ median_income + avg_rooms + population + households + total_rooms + total_bedrooms + housing_median_age + ocean_proximity, data=train)
step(null, scope=list(lower=null,upper=full),direction="forward")
```
```{r}
# Function to print the MSE, Root MSE, and MAE for a given model
m = length(test$median_house_value)
tests= function(model){
  test_MSE = sum((predict(model,test) - test$median_house_value)^2) / m
  test_MAE = sum(abs(predict(model,test) - test$median_house_value)) / m

  cat("MSE: ", test_MSE, "\n")
  cat("RMSE: ",sqrt(test_MSE),"\n")
  cat("MAE:",test_MAE,"\n")
}
```

```{r}
m1 = full
tests(m1)
```
```{r}
m2 = bamV(median_house_value ~ s(median_income,k=4) + avg_rooms + population + households + total_rooms + total_bedrooms + housing_median_age + ocean_proximity, data=train)

tests(m2)
```
```{r}
m3 = bamV(median_house_value ~ s(median_income,k=4) + ocean_proximity, data=train)

tests(m3)
```
```{r}
m4 = bamV(median_house_value ~ s(latitude, longitude) + s(median_income,k=4) + population + households + s(total_rooms,k=3) + total_bedrooms + housing_median_age + ocean_proximity, data=train)

tests(m4)
```
```{r}
print(plot(m4),pages=1,ask=FALSE)
```
```{r}
m5 = qgamV(median_house_value ~ s(latitude, longitude) + s(median_income,k=4) + avg_rooms + population + households + s(total_rooms,k=3) + total_bedrooms + housing_median_age + ocean_proximity, data=train,aQgam = list(discrete = TRUE),qu=0.5)

tests(m5)
```


```{r}
# Function to overlay the distribution of a model's predictions and observational data
compare_hist = function(model,name){
  p1 = hist(predict(model,test))
  p2 = hist(test$median_house_value)
  plot( p1, col=rgb(0,0,1,1/4),ylim=c(0,1300), main="Distribution of Model vs Observational Data")
  plot( p2, col=rgb(1,0,0,1/4),add=T)
  legend("topright",legend=c(name,"Observations"),col=c(rgb(0,0,1,1/4),rgb(1,0,0,1/4)),pch=15)
}

compare_hist(m4,"m4")
```
```{r}
compare_hist(m5,"m5")
```
```{r}
m6 = bamV(median_house_value ~ s(latitude, longitude) + s(median_income,k=4) + population + households + s(total_rooms,k=3) + total_bedrooms + housing_median_age + ocean_proximity + is_max, data=train)

tests(m6)
```
```{r}
m7 = bamV(median_house_value ~ s(latitude, longitude) + s(median_income,k=4) + population + households + s(total_rooms,k=3) + total_bedrooms + housing_median_age + ocean_proximity + is_max + median_income*is_max + , data=train)

tests(m7)
```
```{r}
compare_hist(m6,"m6")
compare_hist(m7,"m7")
```
```{r}
print(plot(m6),pages=1,ask=FALSE)
```

